---
openapi: 3.0.1
info:
  title: API V1
  version: v1
  description: This is the first version of my API
components:
  securitySchemes:
    bearer_auth:
      type: http
      scheme: bearer
      bearerFormat: JWT
paths:
  "/api/v1/cars":
    get:
      summary: list cars
      tags:
      - Cars
      security:
      - bearer_auth: []
      responses:
        '200':
          description: successful
        '201':
          description: authentication passed
        '401':
          description: authentication failed
servers:
- url: https://{defaultHost}
  variables:
    defaultHost:
      default: www.example.com
